/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arifin;

import javax.swing.JOptionPane;

/**
 *
 * @author User-
 */
public class IDEAL extends javax.swing.JFrame {
    String temp="";
    Double tin,bt, h1;
    /**
     * Creates new form IDEAL
     */
    public IDEAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        perempuan = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        bHasil = new javax.swing.JButton();
        bUlang = new javax.swing.JButton();
        bExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tinggi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        berat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setText("BERAT BADAN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(12, 144, 80, 14);

        jLabel4.setText("JENIS KELAMIN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(12, 185, 90, 14);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        jPanel1.add(nama);
        nama.setBounds(105, 48, 173, 30);

        buttonGroup1.add(perempuan);
        perempuan.setText("Perempuan");
        jPanel1.add(perempuan);
        perempuan.setBounds(110, 180, 90, 23);

        buttonGroup1.add(laki);
        laki.setText("Laki-laki");
        jPanel1.add(laki);
        laki.setBounds(245, 181, 80, 23);

        bHasil.setLabel("Hitung");
        bHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHasilActionPerformed(evt);
            }
        });
        jPanel1.add(bHasil);
        bHasil.setBounds(71, 224, 90, 23);

        bUlang.setText("Coba Lagi");
        bUlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUlangActionPerformed(evt);
            }
        });
        jPanel1.add(bUlang);
        bUlang.setBounds(224, 224, 90, 23);

        bExit.setText("Keluar");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        jPanel1.add(bExit);
        bExit.setBounds(402, 224, 80, 23);

        jLabel5.setText("Berat badan ideal anda adalah ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(71, 276, 160, 14);

        jLabel6.setText("Hasil Diagnosa Kesehatan");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(216, 308, 123, 14);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel1.add(hasil);
        hasil.setBounds(71, 331, 400, 20);
        jPanel1.add(saran);
        saran.setBounds(71, 366, 400, 20);

        jLabel9.setText("Cm");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(190, 100, 15, 14);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("CEK TUBUH IDEAL");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(200, 20, 130, 15);

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));
        jPanel2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.setLayout(null);

        jLabel1.setText("NAMA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 60, 50, 20);

        tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinggiActionPerformed(evt);
            }
        });
        jPanel2.add(tinggi);
        tinggi.setBounds(120, 100, 73, 30);

        jLabel2.setText("TINGGI");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 110, 60, 14);

        jLabel8.setText("Kg");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(350, 280, 12, 14);
        jPanel2.add(ideal);
        ideal.setBounds(260, 270, 60, 30);

        jLabel7.setText("Kg");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(220, 150, 12, 14);
        jPanel2.add(berat);
        berat.setBounds(120, 140, 73, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, -10, 600, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaActionPerformed

    private void tinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinggiActionPerformed

    private void bUlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUlangActionPerformed
nama.setText("");
tinggi.setText("");
berat.setText("");
buttonGroup1.clearSelection();
ideal.setText("");
saran.setText("");
hasil.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_bUlangActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    private void bHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHasilActionPerformed

        if(berat.getText().equals("")||tinggi.getText().equals("")||nama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Kotak isian Belum diisi, maka harus diisi");
        }else if (perempuan.isSelected()||laki.isSelected())
            try{
                Proses();
            }
        catch(Exception e) {
           JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
        }
        else {
            JOptionPane.showMessageDialog(null, "Jenis Kelamin silahkan diisi");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_bHasilActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDEAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDEAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDEAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDEAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDEAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bHasil;
    private javax.swing.JButton bUlang;
    private javax.swing.JTextField berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField hasil;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
     tin = Double.valueOf(tinggi.getText());
        bt = Double.valueOf(berat.getText());
        
        if(perempuan.isSelected()){
            h1 = (tin -110) * 1;
        } else if (laki.isSelected()) {
            h1 = (tin - 104) * 1;
        }
        temp = Double.toString(h1.intValue());
        if(h1 <bt) {
            ideal.setText(temp);
            hasil.setText("Maaf"+nama.getText()+",Sepertinya Anda Overweight :(");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol yaa");
        }else if (h1>bt) {
            ideal.setText(temp);
            hasil.setText("Maaf"+nama.getText()+",Sepertinya Anda Underweight :(");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkarbohidrat yaa");
        }else {
            ideal.setText(temp);
            hasil.setText("Yaa"+nama.getText()+",Sepertinya Anda sudah ideal :(");
            saran.setText("Lanjutkan pola makan teratur dan gaya hidup sehat");
    }}}
    

